version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      day: "monday"
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/London"
  - package-ecosystem: "pip"
    allow:
      - dependency-type: all
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/London"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/London"
