services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: django_sveltekit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/django_sveltekit_db
      REDIS_URL: redis://redis:6379/0
      DEBUG: "1"

  celery_worker:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: celery -A project worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/django_sveltekit_db
      REDIS_URL: redis://redis:6379/0
      DEBUG: "1"

  celery_beat:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: celery -A project beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/django_sveltekit_db
      REDIS_URL: redis://redis:6379/0
      DEBUG: "1"

  celery_flower:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: celery -A project flower --address=0.0.0.0 --port=5555
    volumes:
      - ./backend:/app
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/django_sveltekit_db
      REDIS_URL: redis://redis:6379/0
      DEBUG: "1"

  frontend:
    build: ./frontend
    restart: unless-stopped
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      PUBLIC_BASE_API_URL: http://backend:8000
    depends_on:
      - backend

volumes:
  postgres_data:
