version: "3"

volumes:
  db:

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ENVIRONMENT: development
    depends_on:
      - db
    env_file:
      - .env
    image: project_name
    ports:
      - "8000:8000"
    restart: unless-stopped
    tty: true
    volumes:
      - .:/app

  db:
    env_file:
      - .env
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
