[tool.coverage.run]
branch = true
omit = ["manage.py", "project/asgi.py", "project/wsgi.py"]
source = ["."]

[tool.coverage.report]
exclude_lines = [
    "class .*\\bProtocol\\):",
    "@overload",
    "@typing.overload",
    "pragma: no cover",
]
fail_under = 100

[tool.django-stubs]
django_settings_module = "project.settings"

[tool.isort]
profile = "black"

[tool.mypy]
files = "."
plugins = ["mypy_django_plugin.main"]

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["rich.*", "allauth.*"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "project.settings"
addopts = "--cov --numprocesses auto --dist loadscope --reuse-db"
python_files = ["tests.py", "project/**/tests/test_*.py"]
