# Generated by Django 4.2.4 on 2023-08-19 23:18

import project.utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=project.utils.fields.StringField(
                blank=True, max_length=500, null=True
            ),
        ),
    ]
