name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' || !contains(github.ref, 'main') }}

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
      - name: Install dependencies
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry install --no-root

  lint:
    # Dependencies are required for some linters.
    needs: [dependencies]
    uses: ./.github/workflows/lint-python.yml
    with:
      package-manager: poetry

  test:
    needs: [dependencies]
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: project_name
          POSTGRES_PASSWORD: project_name
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - type=tmpfs,destination=/var/lib/postgresql/data
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install --no-install-recommends libproj-dev gdal-bin
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
      - name: Set up environment
        run: cp .env.ci .env
      - name: Install dependencies
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry install --no-root
      - name: Check for missing migrations
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry run python manage.py makemigrations --check --dry-run
      - name: Run system checks
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry run python manage.py check
      - name: Run pytest
        uses: liskin/gh-problem-matcher-wrap@v1
        env:
          ENVIRONMENT: ci
          POSTGRES_HOST: localhost
          PATH: /home/runner/.local/bin:/usr/local/bin:/usr/bin:/bin
        with:
          linters: pytest
          run: poetry run python -m pytest --create-db

  deploy:
    needs: [dependencies, lint, test]
    if: github.ref == 'refs/heads/main' && github.event.repository.name != 'backend-template'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to Dokku
        uses: docker://dokku/ci-docker-image:latest
        env:
          GIT_REMOTE_URL: ${{ secrets.DOKKU_GIT_REMOTE_URL }}
          SSH_PRIVATE_KEY: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          BRANCH: "master"
          CI_BRANCH_NAME: "main"
          GIT_PUSH_FLAGS: "--force"
          TRACE: "1"
        with:
          args: dokku-deploy
