name: Frontend CI/CD

on:
  workflow_call:

defaults:
  run:
    working-directory: frontend

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install backend dependencies
      working-directory: backend
      run: poetry install --no-interaction --no-root

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci

    - name: Sync API types
      working-directory: frontend
      run: npm run sync-types
      env:
        DJANGO_SETTINGS_MODULE: project.settings

    - name: Check if types changed
      run: |
        if git diff --exit-code src/lib/api/schema.d.ts; then
          echo "✅ Types are up to date"
        else
          echo "❌ API types are out of sync. Please run 'npm run sync-types' locally and commit the changes."
          git diff src/lib/api/schema.d.ts
          exit 1
        fi

  test:
    runs-on: ubuntu-latest
    needs: [type-check]

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment variables
      run: cp .env.example .env

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run type checking
      run: npm run check

    - name: Run linting
      run: npm run lint

    - name: Build application
      run: npm run build
