name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/frontend.yml'
      - 'docker-compose.yml'
      - '.pre-commit-config.yaml'
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/frontend.yml'
      - 'docker-compose.yml'
      - '.pre-commit-config.yaml'

defaults:
  run:
    working-directory: frontend

jobs:
  type-sync:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'backend/') || contains(join(github.event.commits.*.modified), 'backend/')

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment variables
      run: cp .env.example .env

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      run: npm ci

    - name: Set up Python (for Django schema generation)
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install backend dependencies
      working-directory: backend
      run: poetry install --no-interaction --no-root

    - name: Sync API types
      run: npm run sync-types
      env:
        DJANGO_SETTINGS_MODULE: project.settings

    - name: Check if types changed
      run: |
        if git diff --exit-code src/lib/api/backend-api-schema.d.ts; then
          echo "Types are up to date"
        else
          echo "Types were updated"
          git diff src/lib/api/backend-api-schema.d.ts
        fi

  test:
    runs-on: ubuntu-latest
    needs: [type-sync]
    if: always() && (needs.type-sync.result == 'success' || needs.type-sync.result == 'skipped')

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment variables
      run: cp .env.example .env

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run type checking
      run: npm run check

    - name: Run linting
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build

    - name: Run pre-commit on frontend files
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --files frontend/**/*
